#!/bin/sh

set -e

# Install Build Dependencies
apk add --update --upgrade --no-cache --virtual .pbnj-build-deps go git musl-dev

# Download Dependencies
go get -v -d

# Compile
go install -v -ldflags "-X main.GitRev=$(git rev-parse --short HEAD)"

# Install Runtime Dependencies
apk add --update --upgrade --no-cache --virtual .pbnj-run-deps ca-certificates ipmitool

# Cleanup
apk del --purge .pbnj-build-deps
rm -rf $GOPATH/pkg/* $GOPATH/src/*
