// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api/v1/diagnostic.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Diagnostic_Screenshot_FullMethodName          = "/github.com.tinkerbell.pbnj.api.v1.Diagnostic/Screenshot"
	Diagnostic_ClearSystemEventLog_FullMethodName = "/github.com.tinkerbell.pbnj.api.v1.Diagnostic/ClearSystemEventLog"
	Diagnostic_SendNMI_FullMethodName             = "/github.com.tinkerbell.pbnj.api.v1.Diagnostic/SendNMI"
)

// DiagnosticClient is the client API for Diagnostic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagnosticClient interface {
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	ClearSystemEventLog(ctx context.Context, in *ClearSystemEventLogRequest, opts ...grpc.CallOption) (*ClearSystemEventLogResponse, error)
	SendNMI(ctx context.Context, in *SendNMIRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type diagnosticClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticClient(cc grpc.ClientConnInterface) DiagnosticClient {
	return &diagnosticClient{cc}
}

func (c *diagnosticClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, Diagnostic_Screenshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticClient) ClearSystemEventLog(ctx context.Context, in *ClearSystemEventLogRequest, opts ...grpc.CallOption) (*ClearSystemEventLogResponse, error) {
	out := new(ClearSystemEventLogResponse)
	err := c.cc.Invoke(ctx, Diagnostic_ClearSystemEventLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticClient) SendNMI(ctx context.Context, in *SendNMIRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Diagnostic_SendNMI_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticServer is the server API for Diagnostic service.
// All implementations must embed UnimplementedDiagnosticServer
// for forward compatibility
type DiagnosticServer interface {
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	ClearSystemEventLog(context.Context, *ClearSystemEventLogRequest) (*ClearSystemEventLogResponse, error)
	SendNMI(context.Context, *SendNMIRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDiagnosticServer()
}

// UnimplementedDiagnosticServer must be embedded to have forward compatible implementations.
type UnimplementedDiagnosticServer struct {
}

func (UnimplementedDiagnosticServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedDiagnosticServer) ClearSystemEventLog(context.Context, *ClearSystemEventLogRequest) (*ClearSystemEventLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSystemEventLog not implemented")
}
func (UnimplementedDiagnosticServer) SendNMI(context.Context, *SendNMIRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNMI not implemented")
}
func (UnimplementedDiagnosticServer) mustEmbedUnimplementedDiagnosticServer() {}

// UnsafeDiagnosticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticServer will
// result in compilation errors.
type UnsafeDiagnosticServer interface {
	mustEmbedUnimplementedDiagnosticServer()
}

func RegisterDiagnosticServer(s grpc.ServiceRegistrar, srv DiagnosticServer) {
	s.RegisterService(&Diagnostic_ServiceDesc, srv)
}

func _Diagnostic_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnostic_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnostic_ClearSystemEventLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSystemEventLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).ClearSystemEventLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnostic_ClearSystemEventLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).ClearSystemEventLog(ctx, req.(*ClearSystemEventLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnostic_SendNMI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServer).SendNMI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diagnostic_SendNMI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServer).SendNMI(ctx, req.(*SendNMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Diagnostic_ServiceDesc is the grpc.ServiceDesc for Diagnostic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Diagnostic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.tinkerbell.pbnj.api.v1.Diagnostic",
	HandlerType: (*DiagnosticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screenshot",
			Handler:    _Diagnostic_Screenshot_Handler,
		},
		{
			MethodName: "ClearSystemEventLog",
			Handler:    _Diagnostic_ClearSystemEventLog_Handler,
		},
		{
			MethodName: "SendNMI",
			Handler:    _Diagnostic_SendNMI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/diagnostic.proto",
}
