// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

var taskStatusStreamDesc = &grpc.StreamDesc{
	StreamName: "Status",
}

func (c *taskClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.pbnj.api.proto.v1.Task/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskService is the service API for Task service.
// Fields should be assigned to their respective handler implementations only before
// RegisterTaskService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type TaskService struct {
	Status func(context.Context, *StatusRequest) (*StatusResponse, error)
}

func (s *TaskService) status(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/github.com.tinkerbell.pbnj.api.proto.v1.Task/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterTaskService registers a service implementation with a gRPC server.
func RegisterTaskService(s grpc.ServiceRegistrar, srv *TaskService) {
	srvCopy := *srv
	if srvCopy.Status == nil {
		srvCopy.Status = func(context.Context, *StatusRequest) (*StatusResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "github.com.tinkerbell.pbnj.api.proto.v1.Task",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Status",
				Handler:    srvCopy.status,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "api/proto/v1/task.proto",
	}

	s.RegisterService(&sd, nil)
}
