FROM golang:1.15

ENV GO111MODULE=on

RUN apt update; apt install -y protobuf-compiler && \
    go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0.1 && \
    go get google.golang.org/grpc@v1.32.0 && \
    go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0 && \
    go get golang.org/x/tools/cmd/goimports